# -*- mode: ruby -*-
# vi: set ft=ruby :

$hosts_script = <<SCRIPT
sudo apt-get install software-properties-common
sudo apt-add-repository ppa:ansible/ansible
apt-get update
export DEBIAN_FRONTEND=noninteractive
apt-get -q -y --force-yes install ansible
SCRIPT

Vagrant.configure(2) do |config|
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false
  config.vm.box = "hashicorp/precise64"
  config.vm.hostname = "ansible"
  config.vm.provider :virtualbox do |v|
    v.name = "ansible"
    v.customize ["modifyvm", :id, "--memory", "2048"]
  end
  config.vm.network :private_network, ip: "10.211.55.106"
  config.vm.provision :shell, :inline => $hosts_script
  config.vm.provision :hostmanager
end
